import type { Metadata } from "next";
import { Manrope, Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";
import css from "./layout.module.css";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";

const manrope = Manrope({
  variable: "--font-family",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  variable: "--second-family",
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${inter.variable}`}>
      <body>
        <TanStackProvider>
          <header className={css.headerContainer}>
            <Link href="/" aria-label="Go to homepage">
              <Image
                src="/logo.svg"
                alt="RentalCar"
                width={104}
                height={16}
                priority
              />
            </Link>
            <nav>
              <ul className={css.navList}>
                <li className={css.navListElement}>
                  <Link href="/" aria-label="Go to homepage">
                    Home
                  </Link>
                </li>
                <li className={css.navListElement}>
                  <Link href="/catalog" aria-label="Go to catalog page">
                    Catalog
                  </Link>
                </li>
              </ul>
            </nav>
          </header>
          <main>
            {children}
          </main>
        </TanStackProvider>
      </body>
    </html>
  );
}
